// Packs Global AI's operating documents into a server module, so every build (and any later bundle) carries
// the documents that match its code instead of reading a checkout at runtime. Runs before dev, build, typecheck and tests.
import { lstat, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const DOCUMENTS = {
  'README.md': 'overview and current status',
  'docs/WORKFLOWS.md': 'operating guidance; explicitly labelled future sections may be present',
  'docs/TERMINAL-PROTOCOL.md': 'terminal operations and current recovery contract',
  'docs/SETUP.md': 'installed-host setup',
  'docs/GLOBAL-AI.md': 'Global AI A1 capabilities and limitations',
  'docs/BACKGROUND-ASSISTANT.md': 'Agents tab, deterministic attention, and what the Background assistant does and does not do yet',
  'shared/openapi.yaml': 'Exact app HTTP paths and input schemas for Background action requests; use search_docs and bounded read_doc ranges',
};
const LIMIT = 256 * 1024;
const web = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const OUTPUT = join(web, 'src/server/global-ai/kb.generated.ts');

/** Only ordinary, bounded files under the repository root are packed; a symlink or oversized document fails the build. */
export async function buildKnowledgeBase(root) {
  const documents = [];
  for (const [name, description] of Object.entries(DOCUMENTS)) {
    const path = join(root, name), info = await lstat(path);
    const limit = name === 'shared/openapi.yaml' ? 1024 * 1024 : LIMIT;
    if (!info.isFile() || info.isSymbolicLink() || info.size > limit) throw new Error(`${name} must be an ordinary file of at most ${limit} bytes.`);
    documents.push({ name, description, content: await readFile(path, 'utf8') });
  }
  return { documents };
}
export function moduleSource(kb) {
  return `// Generated by scripts/build-kb.mjs from the repository documents. Do not edit; it is rebuilt before dev, build, typecheck and tests.
import type { KnowledgeBase } from './reads.ts';
export const KB: KnowledgeBase = ${JSON.stringify(kb, null, 1)};
`;
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  const source = moduleSource(await buildKnowledgeBase(resolve(web, '..')));
  // Rewriting identical output would trigger a needless dev reload.
  if (await readFile(OUTPUT, 'utf8').catch(() => '') !== source) await writeFile(OUTPUT, source);
}
